### ISSUE TITLE
vision AI 調査

### ISSUE THREAD

**Issue by moririn2528** [jphacks/D_2202#12]
https://pkg.go.dev/cloud.google.com/go/vision/v2/apiv1#hdr-Example_usage
この辺を使って、golang からどう使うか、それともアプリから API で呼び出すかなどを調査してほしい

**Comment by yu0ki** [comment]
使えるか使えないか判断

**Comment by yu0ki** [comment]
vision API : 写真をツッコむと植物の種類が返ってくる
こいつをGoで使用できるか
精度は実用に耐えるか
サーバー or API （楽そうなほう選ぶ。Goが楽そうだがβ）

最終的に、サンプルづくりまで行けたらいいな

**Comment by yu0ki** [comment]
10/16 進捗
[とりあえず感想書いた](https://docs.google.com/presentation/d/1-NI9scQV16oYC5vYrozoCZLZKySm7_FE/edit?usp=sharing&ouid=101540506980322036537&rtpof=true&sd=true)

> 要約すると

> いくつか使えそうな機能があるが、まだ動かせてないので精度とかは良く分からん

> go で実装するとよさそう

**Comment by yu0ki** [comment]
WEB_DETECTORの Entities のスコア最大値の単語が、だいたい正解の植物名である

**Comment by yu0ki** [comment]
### **今のところの結論（簡単に）**

vision APIのWEB_DETECTIONという機能で、画像から植物の名前を特定できそう。

特定に使用するのは[ImageAnnotatorClient](https://pkg.go.dev/cloud.google.com/go/vision/apiv1#ImageAnnotatorClient) クラスのメソッド[DetectWeb](https://pkg.go.dev/cloud.google.com/go/vision/apiv1#ImageAnnotatorClient.DetectWeb)

**DetectWebの入出力**

- 入力：context.Background()という謎のやつと、判定したい画像ファイル, そしてnil 
- 出力：[WebDetection型](https://pkg.go.dev/google.golang.org/genproto/googleapis/cloud/vision/v1#WebDetection)。

詳しいことは[vision api についてまとめ](https://docs.google.com/presentation/d/1-NI9scQV16oYC5vYrozoCZLZKySm7_FE/edit?usp=sharing&ouid=101540506980322036537&rtpof=true&sd=true)を見てください
